version: '3.7'

services:
  api-gateway:
    image: docker.io/anirudhloona26/ghumantu-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    networks:
      - ghumantu
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka

  service-registry:
    image: docker.io/anirudhloona26/ghumantu-service-registry:0.0.1-SNAPSHOT
    networks:
      - ghumantu
    ports:
      - "8761:8761"

  auth-service:
    image: docker.io/anirudhloona26/ghumantu-auth-service:0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
    networks:
      - ghumantu
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka

  qanda-service:
    image: docker.io/anirudhloona26/ghumantu-qanda-service:0.0.1-SNAPSHOT
    ports:
      - "9097:9097"
    networks:
      - ghumantu
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka

  place-service:
    image: docker.io/anirudhloona26/ghumantu-place-service:0.0.1-SNAPSHOT
    ports:
      - "9091:9091"
    networks:
      - ghumantu
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka

  review-service:
    image: docker.io/anirudhloona26/ghumantu-review-service:0.0.1-SNAPSHOT
    ports:
      - "9095:9095"
    networks:
      - ghumantu
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka


networks:
  ghumantu: