version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - ghumantu

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    networks:
      - ghumantu
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  ticket-service:
    image: docker.io/anirudhloona26/ghumantu-ticket-service:0.0.1-SNAPSHOT
    ports:
      - "9093:9093"
    networks:
      - ghumantu
    depends_on:
      - kafka
      - service-registry
      - postgres
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.KAFKA.BOOTSTRAPSERVERS: kafka:9092
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/ticket_service
      SPRING.DATASOURCE.PASSWORD: 12341234

  payment-service:
    image: docker.io/anirudhloona26/ghumantu-payment-service:0.0.1-SNAPSHOT
    ports:
      - "9094:9094"
    networks:
      - ghumantu
    depends_on:
      - service-registry
      - kafka
      - postgres
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.KAFKA.BOOTSTRAPSERVERS: kafka:9092
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/payment_service
      SPRING.DATASOURCE.PASSWORD: 12341234

  email-service:
    image: docker.io/anirudhloona26/ghumantu-email-service:0.0.1-SNAPSHOT
    ports:
      - "9096:9096"
    networks:
      - ghumantu
    depends_on:
      - service-registry
      - kafka
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.KAFKA.BOOTSTRAPSERVERS: kafka:9092

  api-gateway:
    image: docker.io/anirudhloona26/ghumantu-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    networks:
      - ghumantu
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka

  service-registry:
    image: docker.io/anirudhloona26/ghumantu-service-registry:0.0.1-SNAPSHOT
    networks:
      - ghumantu
    ports:
      - "8761:8761"

  auth-service:
    image: docker.io/anirudhloona26/ghumantu-auth-service:0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
    networks:
      - ghumantu
    depends_on:
      - service-registry
      - postgres
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.KAFKA.BOOTSTRAPSERVERS: kafka:9092
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/auth_service
      SPRING.DATASOURCE.PASSWORD: 12341234

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - ghumantu
    environment:
      - POSTGRES_PASSWORD=Anirudh@35
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    container_name: postgres_x
    restart: always
    volumes:
      - E:\postgres_docker_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - ghumantu
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=anirudhloona26@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12341234

  qanda-service:
    image: docker.io/anirudhloona26/ghumantu-qanda-service:0.0.1-SNAPSHOT
    ports:
      - "9097:9097"
    networks:
      - ghumantu
    depends_on:
      - service-registry
      - postgres
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/qanda_service
      SPRING.DATASOURCE.PASSWORD: 12341234

  place-service:
    image: docker.io/anirudhloona26/ghumantu-place-service:0.0.1-SNAPSHOT
    ports:
      - "9091:9091"
    networks:
      - ghumantu
    depends_on:
      - service-registry
      - review-service
      - postgres
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/place_service
      SPRING.DATASOURCE.PASSWORD: 12341234

  review-service:
    image: docker.io/anirudhloona26/ghumantu-review-service:0.0.1-SNAPSHOT
    ports:
      - "9095:9095"
    networks:
      - ghumantu
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/review_service
      SPRING.DATASOURCE.PASSWORD: 12341234

networks:
  ghumantu: